app_identifier "com.adamtecle.Bibliio" # The bundle identifier of your app

username "adam.tecle@gmail.com" # your Apple ID user

submit_for_review true

app_review_information(
    first_name: "Adam",
    last_name: "Tecle",
    phone_number: "6097125277",
    email_address: "adam.tecle@gmail.com"
)

automatic_release true
