fastlane_version "1.108.0"

default_platform :ios

platform :ios do
 
  before_all do
    build_number = Time.new.strftime("%Y.%m.%d")
    increment_build_number build_number: build_number
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new build to HockeyApp"
  lane :beta do
    # Build
    gym(
      workspace: "Bibliio.xcworkspace",  
      scheme: "Bibliio"
    )

    # Push to Hockey
    hockey(
      api_token: ENV['HOCKEY_API_TOKEN'],
      notify: "1"
    )

  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
   # Build
    gym(
      use_legacy_build_api: true,
      workspace: "Bibliio.xcworkspace",
      scheme: "Bibliio"
    )
    
    deliver(force: true)
    # frameit
  end


  after_all do |lane|
    clean_build_artifacts
  end

  error do |lane, exception|
  end

end
