# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 7 Plus",
  "iPhone 7",
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5"
])

languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
scheme "Bibliio"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
workspace "./Bibliio.xcworkspace"

